/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whjz_io_JniNative */

#ifndef _Included_com_whjz_io_JniNative
#define _Included_com_whjz_io_JniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whjz_io_JniNative
 * Method:    GPIO_SETDIRECTION
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_GPIO_1SETDIRECTION
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    GPIO_OUT_BATTRY
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_GPIO_1OUT_1BATTRY
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    GPIO_IN_BATTRY
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_whjz_io_JniNative_GPIO_1IN_1BATTRY
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    UART_SEL
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_UART_1SEL
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    UART_OPEN
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jobject JNICALL Java_com_whjz_io_JniNative_UART_1OPEN
  (JNIEnv *, jclass, jstring, jint);


/*
 * Class:     com_whjz_io_JniNative
 * Method:    UART_CLOSE
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_UART_1CLOSE
  (JNIEnv *, jclass );

/*
 * Class:     com_whjz_io_JniNative
 * Method:    UART_SET_OPT
 * Signature: (IICI)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_UART_1SET_1OPT
  (JNIEnv *, jclass,jint, jint, jchar, jint);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    PWMBUZ_APP_PWM_OUT
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_PWMBUZ_1APP_1PWM_1OUT
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    PWMBUZ_SET_FRE
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_PWMBUZ_1SET_1FRE
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    PWMBUZ_SET_DUTY
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_PWMBUZ_1SET_1DUTY
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    PWMBUZ_RUNORCLOSE
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_PWMBUZ_1RUNORCLOSE
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    TEMP_START
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_whjz_io_JniNative_TEMP_1START
  (JNIEnv *, jclass);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    TEMP_CATTEMP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_whjz_io_JniNative_TEMP_1CATTEMP
  (JNIEnv *, jclass);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    TEMP_CATSPEED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_whjz_io_JniNative_TEMP_1CATSPEED
  (JNIEnv *, jclass);

/*
 * Class:     com_whjz_io_JniNative
 * Method:    ADREAD
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_whjz_io_JniNative_ADREAD
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
